### ISSUE TITLE
打包成Docker

### ISSUE THREAD

**Issue by Keycatowo** [Keycatowo/audioviz-webui#14]

**Comment by Keycatowo** [comment]
## 問題說明
要建立Dockerhub CI的時候遇到問題
![image](https://user-images.githubusercontent.com/47293699/224070535-489cdd2d-2d20-427a-abb4-a2e542e4b584.png)
看起來是名稱錯誤
![image](https://user-images.githubusercontent.com/47293699/224070782-53814999-c095-4ee2-ada8-231251f4029e.png)


## 解決方式
嘗試用git tags
```yaml
name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get latest Git tag
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-docker-image-name:${{ steps.get_tag.outputs.tag }}
```
